### PR TITLE
add gloves elements

### PR DESCRIPTION
**Pull request by DonJoan**
Hello, I am happy to see this resource work again and i will help you

### CODE REVIEW

**Comment by LostJ3ster** [comment]
Thanks for providing help. I will take a look at your PRs today and merge them if they work flawlessly

**Comment by DonJoan** [comment]
Please test gloves and if there is any problem 
tell me

**Comment by LostJ3ster** [comment]
I just saw that you haven’t used my workaround functions.
I did some tests with your PRs, but ran into some issues. I will do further investigation this evening.

**Comment by DonJoan** [comment]
image
missing hairs

**Comment by LostJ3ster** [comment]
> image
> missing hairs,eyes

I will have a look at it too.
I‘m just testing with the “/character“ command so far.

**Comment by DonJoan** [comment]
Gloves list missing in V clothingnames
Can you make one

**Comment by DonJoan** [comment]
Do you check this lists for clothes, props etc from new dlc
Do you have a discord

**Comment by LostJ3ster** [comment]
> Gloves list missing in V clothingnames Can you make one

In your PR you're refering to Component ID 3, therefore it's Male/Female Torsos.
I just double checked and found it in his repo.


> Do you check this lists for clothes, props etc from new dlc Do you have a discord

Good note. I haven't checked for the new dlc's. Based on his last update 5 month ago I'd say the lists aren't up to date.
Not quite sure when the last clothing update released tbh.

My Discord is LostJ3ster#2728. Just message me there if you want to do further testing-talks there.

**Comment by LostJ3ster** [comment]
cui_character - Hair tab

For me Hair is there. What I just found out testing it is the following:
Entering the Hair-Tab with hair id > 0 and hair id < 37 (and maybe hair id > 73 too) will result in your problem, as all hairs are manually inserted in "ui/pages/optional/hair_male.html" (or ".../hair_female.html" for female).

If your hair id is out of option index bounds, it cant display anything, and will not display anything on change.
This must be an issue with the original cui_character rather than my fork.

**Comment by LostJ3ster** [comment]
As by my last tests your PRs didn't cause any problems anymore I'll merge your PRs now.
(Was testing with a fresh installation now, instead of a highly modified cui_character like I'm used to)

**Comment by LostJ3ster** [comment]
> Do you check this lists for clothes, props etc from new dlc Do you have a discord

Depending on [this](https://wiki.rage.mp/index.php?title=Clothes) list, the v-clothingnames Repo is up to date. I compared the amount of components/props (not textures).

**Pull request merged**
